# numpy - numerical python

In [3]:
import numpy as np

## 1. Create an arry using python list or tuple

In [1]:
lst = [1,2,3,4,5]
print(lst)

[1, 2, 3, 4, 5]


In [4]:
arr = np.array(lst)
print(type(arr) , arr)

<class 'numpy.ndarray'> [1 2 3 4 5]


In [5]:
arr = np.array((2,3,4,5))
print(type(arr) , arr)

<class 'numpy.ndarray'> [2 3 4 5]


In [ ]:
0d - 65 - scalar
1d array - vector
2d array
3d array
nd array

In [ ]:
# few important attributes

- size
- shape
- ndim

In [6]:
arr

array([2, 3, 4, 5])

In [7]:
arr.size  # number of element present in an array

4

In [8]:
arr.shape # shape of an matrix

(4,)

In [9]:
arr.ndim # dimesion of an array

1

multi dimensional

In [14]:
lst1 = [[2,4,6,8]]
arr2 = np.array(lst1)

In [15]:
arr2

array([[2, 4, 6, 8]])

In [16]:
arr2.size

4

In [17]:
arr2.shape

(1, 4)

In [18]:
arr2.ndim

2

In [ ]:
2. Create an array with an arange function

arange = likne built-in range but return nd array

In [20]:
arr3 = np.arange(20)

In [21]:
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [23]:
arr3.size

20

In [24]:
arr3.shape

(20,)

In [25]:
arr3.ndim

1

In [26]:
np.arange(3,20,-1)

# 3 , 20 ---> left to right
# -1 ---> right to left

array([], dtype=int64)

In [27]:
np.arange(20,3,-1)

array([20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4])

In [ ]:
# array is a collection of homogenous values

3. create an array with an linespace

In [29]:
np.linspace(1,10,100)

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

In [45]:
# 4. zeros

np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [32]:
# 5. zero_like 

np.zeros_like(arr3)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [33]:
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [49]:
#6 ones

arr4 = np.ones((2,4))

In [50]:
#7 ones_like

np.ones_like(arr4)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [39]:
#8 eye - identity matrix

- sqaure - rows and columns
- dig ele will be one and rest will be zero

dict_keys([1, 2])

In [48]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [56]:
#9 random.rand

np.random.rand(3,1)

array([[0.86790001],
       [0.18085029],
       [0.5890982 ]])

In [57]:
# Reshaping of a matrix

In [58]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [59]:
a.ndim

1

In [62]:
b = a.reshape(2,3)
print(b)

ValueError: cannot reshape array of size 6 into shape (2,2)

In [61]:
b.ndim

2

In [ ]:
shape = number of elements

vector - 6

(1,6)
(2,3)
(3,2)
(6,1)

In [64]:
arr5 = np.arange(15).reshape(15,1)

In [67]:
arr5.reshape(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [70]:
Asian_countries = np.array(["India" , 'pakistan' , 'china' , 'japan' , 'Sri lanka' , 'thailand' , 'bangladesh',
                            "Nepal" , "bhutan" , 'indonasia'])

In [71]:
Asian_countries

array(['India', 'pakistan', 'china', 'japan', 'Sri lanka', 'thailand',
       'bangladeshasdasdasdad', 'Nepal', 'bhutan', 'indonasia'],
      dtype='<U21')

In [73]:
Asian_countries.reshape(5,2)

array([['India', 'pakistan'],
       ['china', 'japan'],
       ['Sri lanka', 'thailand'],
       ['bangladeshasdasdasdad', 'Nepal'],
       ['bhutan', 'indonasia']], dtype='<U21')

In [76]:
# infered

# - specify only one dimesion(and infer the other) when reshaping

array([[1212344423423423432, 121212121212121211212]], dtype=object)

In [78]:
Asian_countries.reshape(-1,2)

array([['India', 'pakistan'],
       ['china', 'japan'],
       ['Sri lanka', 'thailand'],
       ['bangladeshasdasdasdad', 'Nepal'],
       ['bhutan', 'indonasia']], dtype='<U21')

In [80]:
Asian_countries.reshape(-1,1,1)

array([[['India'],
        ['pakistan'],
        ['china'],
        ['japan'],
        ['Sri lanka']],

       [['thailand'],
        ['bangladeshasdasdasdad'],
        ['Nepal'],
        ['bhutan'],
        ['indonasia']]], dtype='<U21')

In [ ]:
row,column , dept
 10     1 ,  1

In [ ]:
# transpose of a matrix

n*m --> m*n

In [85]:
a2 = np.arange(18).reshape(6,3)
a2.shape , a2

((6, 3),
 array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]]))

In [86]:
a2.T

array([[ 0,  3,  6,  9, 12, 15],
       [ 1,  4,  7, 10, 13, 16],
       [ 2,  5,  8, 11, 14, 17]])

In [ ]:
# ravel - converting any dim matrix to 1 dim matrix

In [87]:
a2

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [88]:
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [89]:
# flatten
a2.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [90]:
# Arithmatic operation on array (element wise)

In [102]:
a = np.array([10,20,30,4])
b = np.array([5,10,15,20])

In [103]:
a + b

array([15, 30, 45, 24])

In [93]:
a - b

array([  5,  10,  15, -16])

In [94]:
a / b

array([2. , 2. , 2. , 0.2])

In [95]:
a**3

array([ 1000,  8000, 27000,    64])

In [96]:
a%2

array([0, 0, 0, 0])

In [97]:
a<30

array([ True,  True, False,  True])

In [104]:
a*b # element 

array([ 50, 200, 450,  80])

In [110]:
a = np.arange(20).reshape(4,5)
b = np.arange(15).reshape(5,3)

In [111]:
c = a.dot(b)

In [112]:
a.shape , b.shape , c.shape

((4, 5), (5, 3), (4, 3))

In [113]:
b.dot(a)

ValueError: shapes (5,3) and (4,5) not aligned: 3 (dim 1) != 4 (dim 0)

In [114]:
# unary operation

array_1 = np.array([21,10,15,20])

In [115]:
# Computing the sum of all the elements
array_1.sum()

66

In [116]:
# max element in an array
array_1.max()

21

In [117]:
# max element in an array
array_1.min()

10

In [119]:
# 2d matrix 

num = np.arange(24).reshape(4,6)

In [120]:
num

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [121]:
# Computing the sum of all the elements
num.sum()

276

In [122]:
# axis = 0 means column wise and 1 mean rowise
num.sum(axis = 0)

array([36, 40, 44, 48, 52, 56])

In [123]:
# axis = 0 means column wise and 1 mean rowise
num.sum(axis = 1)

array([ 15,  51,  87, 123])

In [124]:
# axis = 0 means column wise and 1 mean rowise
num.max(axis = 0)

array([18, 19, 20, 21, 22, 23])

In [125]:
# axis = 0 means column wise and 1 mean rowise
num.max(axis = 1)

array([ 5, 11, 17, 23])

In [127]:
# 
Asian_countries.min()

TypeError: cannot perform reduce with flexible type

In [128]:
# unviersal functions

a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [129]:
a = np.array([10,20,30,4])
b = np.array([5,10,15,20])

In [130]:
a + b

array([15, 30, 45, 24])

In [132]:
np.add(a,b)

array([15, 30, 45, 24])

In [133]:
np.subtract(a,b)

array([  5,  10,  15, -16])

In [134]:
np.multiply(a,b)

array([ 50, 200, 450,  80])

In [135]:
np.log(a)

array([2.30258509, 2.99573227, 3.40119738, 1.38629436])

In [136]:
np.sqrt(a)

array([3.16227766, 4.47213595, 5.47722558, 2.        ])

In [137]:
np.sin(a)

array([-0.54402111,  0.91294525, -0.98803162, -0.7568025 ])

In [138]:
np.mean(a)

16.0

In [139]:
np.median(a)

15.0

In [140]:
np.std(a)

9.899494936611665

In [141]:
np.var(a)

98.0

In [142]:
dir(np)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'MachAr',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__dir__',
 '__doc__',
 '__file__',
 '__getattr__',
 '__git_revision__',
 '__loader__',
 '__mkl_version__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_ad

In [143]:
a

array([10, 20, 30,  4])

In [147]:
np.arange(20).reshape(4,5).mean(axis = 0)

array([ 7.5,  8.5,  9.5, 10.5, 11.5])

In [148]:
# iterating

In [149]:
a = np.array([1,2,3,4,5])

In [150]:
for i in a:
    print(i)

1
2
3
4
5


In [151]:
b = np.arange(20).reshape(4,5)

In [152]:
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [153]:
for i in b:
    print(i)

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]
[15 16 17 18 19]


In [154]:
for i in b:
    for j in i:
        print(j)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [155]:
for i in b.flatten():
    print(i)


0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [156]:
np.arange(20).reshape(2,5,2).mean(axis = 0) 

array([[ 5.,  6.],
       [ 7.,  8.],
       [ 9., 10.],
       [11., 12.],
       [13., 14.]])

In [157]:
np.arange(20).reshape(2,5,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])