# Indexing and slicing in array

In [5]:
import numpy as np

In [9]:
a = np.arange(10)

In [10]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
# indexing

a[0]

0

In [14]:
# slicing
a[::-1]

a[1:5:-1]

array([], dtype=int64)

In [15]:
a = np.arange(10).reshape(5,2)

In [22]:
a[::-1][1]

# syntax
# a[row,column]

array([6, 7])

In [18]:
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [19]:
a[1,1]

3

In [20]:
a[::-1,1]

array([9, 7, 5, 3, 1])

In [23]:
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [24]:
a1  = np.arange(25).reshape(5,5)

In [25]:
a1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [26]:
a1[1,2:4]

array([7, 8])

In [27]:
a1[3:,3:]

array([[18, 19],
       [23, 24]])

In [30]:
a1[::1,::2]

array([[ 0,  2,  4],
       [ 5,  7,  9],
       [10, 12, 14],
       [15, 17, 19],
       [20, 22, 24]])

In [32]:
# Counting

In [33]:
# how many values are less than 6

np.sum(a1<6)

6

In [34]:
a1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [35]:
a1<6

array([[ True,  True,  True,  True,  True],
       [ True, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False]])

In [36]:
#how many values less thean 6 in each column

np.sum(a1<6, axis = 0)

array([2, 1, 1, 1, 1])

In [40]:
# any
# Are there any values greater than 8

np.any(a1>100)

False

In [43]:
#all - - are all values less than 10

np.all(np.zeros((1,4)))

False

In [45]:
a1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [49]:
np.all(a1)

False

In [50]:
import numpy as np 
x = np.array([1, 2, 3, 4]) 
print("Original array:") 
print(x) 
print("Test if none of the elements of the said array is zero:") 
print(np.all(x)) 

x = np.array([0, 1, 2, 3]) 
print("Original array:") 
print(x) 
print("Test if none of the elements of the said array is zero:") 
print(np.all(x))  

Original array:
[1 2 3 4]
Test if none of the elements of the said array is zero:
True
Original array:
[0 1 2 3]
Test if none of the elements of the said array is zero:
False


In [ ]:
# splitting of Array

# syntax

numpy.split(ary , sections , axis)

In [57]:
a = np.arange(12)*10

In [58]:
a

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110])

In [55]:
np.split(a,6)

[array([0, 1]),
 array([2, 3]),
 array([4, 5]),
 array([6, 7]),
 array([8, 9]),
 array([10, 11])]

In [60]:
np.split(a,[1,5,8])

[array([0]),
 array([10, 20, 30, 40]),
 array([50, 60, 70]),
 array([ 80,  90, 100, 110])]

In [61]:
arr2 = np.arange(36).reshape(6,6)

In [62]:
arr2

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [63]:
np.split(arr2 , 2 , axis = 1)

[array([[ 0,  1,  2],
        [ 6,  7,  8],
        [12, 13, 14],
        [18, 19, 20],
        [24, 25, 26],
        [30, 31, 32]]),
 array([[ 3,  4,  5],
        [ 9, 10, 11],
        [15, 16, 17],
        [21, 22, 23],
        [27, 28, 29],
        [33, 34, 35]])]

In [64]:
np.split(arr2 , [1,5] , axis = 1)

[array([[ 0],
        [ 6],
        [12],
        [18],
        [24],
        [30]]),
 array([[ 1,  2,  3,  4],
        [ 7,  8,  9, 10],
        [13, 14, 15, 16],
        [19, 20, 21, 22],
        [25, 26, 27, 28],
        [31, 32, 33, 34]]),
 array([[ 5],
        [11],
        [17],
        [23],
        [29],
        [35]])]

In [65]:
np.split(arr2 , [1,5] , axis = 0)

[array([[0, 1, 2, 3, 4, 5]]),
 array([[ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29]]),
 array([[30, 31, 32, 33, 34, 35]])]

In [66]:
np.hsplit(arr2 , 2)

[array([[ 0,  1,  2],
        [ 6,  7,  8],
        [12, 13, 14],
        [18, 19, 20],
        [24, 25, 26],
        [30, 31, 32]]),
 array([[ 3,  4,  5],
        [ 9, 10, 11],
        [15, 16, 17],
        [21, 22, 23],
        [27, 28, 29],
        [33, 34, 35]])]

In [67]:
np.vsplit(arr2 , 2)

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17]]),
 array([[18, 19, 20, 21, 22, 23],
        [24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]])]

In [ ]:
# slicing and indexing
# sum
#any
# all
# split (axis / method)

In [ ]:
wednest numpy_part_3 , pandas_intro
thrusday - pandas_part2
friday - pandas_part3 , matplotlib
monday - searborn , uscase